### ISSUE TITLE
Source code of app in openfisca.fr vignette

### ISSUE THREAD

**Issue by guillett** [cbenz/openfisca-elm-ui#5]
The latest commit on `master` (once _hackily_ fixed) is quite different from
[the vignette picture on openfisca.fr](https://www.openfisca.fr/elements/images/vignette-ui.png).

@cbenz, what is a good (re)starting point ?

Great thanks

**Comment by cbenz** [comment]
@guillett I'm sorry, I think I don't really understand the question!

Here are some elements of explanation perhaps useful.

The *vignette* is a screenshot from the deprecated UI we started developing in 2014. This UI did not follow the Web API evolutions and became non-functional. It is here: https://github.com/openfisca/openfisca-web-ui-legacy

I restarted about 1 year ago another demonstrator, which is this github project (https://github.com/openfisca/demonstrator). This is the project deployed on https://ui.openfisca.fr/ and is simpler than the old UI (ie remove backend with MongoDB + Python, use D3.js charts instead of the hand-crafted waterfall). I spent only a couple of days writing it.

The old UI was designed as a sandbox to test the complete tax and benefit system. But we learned that this approach was too complex, and that dedicated UIs were better. This new demonstrator was designed to play with the salary of the parents of a family, and see the impact on the total income, not more.

Hope it's more clear.

**Comment by cbenz** [comment]
Now I'm surprised because I just discovered that this project https://github.com/openfisca/demonstrator has a branch https://github.com/openfisca/demonstrator/tree/demonstrator_for_new_endpoint which is in itself a complete rewrite of the demonstrator I started one year ago!

This is the one deployed here: https://www.openfisca.fr/demo

Perhaps that would be better to remove https://ui.openfisca.fr/ (which is broken), and transform it into a personal project of mine. What would you say about that?
